name: Test

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - name: "Checkout Sources"
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Create reports directory
        run: |
          mkdir -p build/reports

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          java-version: '23'
          distribution: 'oracle'

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@af1da67850ed9a4cedd57bfd976089dd991e2582 # v4.0.0

      - name: Check Formatting
        run: ./gradlew spotlessCheck

      - name: Run Tests
        run: ./gradlew test

      - name: Prepare coverage report
        run: ./gradlew jacocoRootReport

      - name: Run codacy-coverage-reporter
        uses: codacy/codacy-coverage-reporter-action@v1.3.0
        with:
          project-token: ${{ secrets.CODACY_PROJECT_TOKEN }}
          coverage-reports: build/reports/jacoco/jacocoRootReport/jacocoRootReport.xml